# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 16:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_errand_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
